// location_localization_ext.dart
import 'package:flutter/widgets.dart';
import 'package:pharmacy_app/l10n/locations/location_localizations.dart';

extension LocationLocalizationExt on BuildContext {
  /// GOVERNORATES
  String govLabel(String key) {
    final tr = LocationLocalizations.of(this)!;
    switch (key) {
      case "damascus":
        return tr.gov_damascus;
      case "rural_damascus":
        return tr.gov_rural_damascus;
      case "aleppo":
        return tr.gov_aleppo;
      case "homs":
        return tr.gov_homs;
      case "hama":
        return tr.gov_hama;
      case "latakia":
        return tr.gov_latakia;
      case "tartous":
        return tr.gov_tartous;
      case "idlib":
        return tr.gov_idlib;
      case "daraa":
        return tr.gov_daraa;
      case "deir_ezzor":
        return tr.gov_deir_ezzor;
      case "raqqa":
        return tr.gov_raqqa;
      case "hasakah":
        return tr.gov_hasakah;
      case "quneitra":
        return tr.gov_quneitra;
      case "as_suwayda":
        return tr.gov_as_suwayda;
      default:
        return key;
    }
  }

  /// CITIES (All Cities)
  String cityLabel(String key, {String? governorateKey}) {
    final tr = LocationLocalizations.of(this)!;
    final resolvedKey = _resolveCityKey(key, governorateKey);
    switch (resolvedKey) {
      // Damascus
      case "city_damascus_mazzeh":
        return tr.city_damascus_mazzeh;
      case "city_damascus_kafrsouseh":
        return tr.city_damascus_kafrsouseh;
      case "city_damascus_barzeh":
        return tr.city_damascus_barzeh;
      case "city_damascus_meidan":
        return tr.city_damascus_meidan;
      case "city_damascus_ruken_al_din":
        return tr.city_damascus_ruken_al_din;
      case "city_damascus_bab_touma":
        return tr.city_damascus_bab_touma;
      case "city_damascus_bab_sharqi":
        return tr.city_damascus_bab_sharqi;
      case "city_damascus_tishreen":
        return tr.city_damascus_tishreen;
      case "city_damascus_al_qanawat":
        return tr.city_damascus_al_qanawat;
      case "city_damascus_abu_rummaneh":
        return tr.city_damascus_abu_rummaneh;
      case "city_damascus_shaalan":
        return tr.city_damascus_shaalan;
      case "city_damascus_dummar":
        return tr.city_damascus_dummar;
      case "city_damascus_al_midan":
        return tr.city_damascus_al_midan;
      case "city_damascus_kassaa":
        return tr.city_damascus_kassaa;
      case "city_damascus_old_damascus":
        return tr.city_damascus_old_damascus;
      case "city_damascus_qasioun":
        return tr.city_damascus_qasioun;
      case "city_damascus_adawi":
        return tr.city_damascus_adawi;
      case "city_damascus_al_amara":
        return tr.city_damascus_al_amara;
      case "city_damascus_abu_jamal":
        return tr.city_damascus_abu_jamal;
      case "city_damascus_harika":
        return tr.city_damascus_harika;

      // Rural Damascus
      case "city_rural_damascus_douma":
        return tr.city_rural_damascus_douma;
      case "city_rural_damascus_harasta":
        return tr.city_rural_damascus_harasta;
      case "city_rural_damascus_zamalka":
        return tr.city_rural_damascus_zamalka;
      case "city_rural_damascus_jobar":
        return tr.city_rural_damascus_jobar;
      case "city_rural_damascus_qaboun":
        return tr.city_rural_damascus_qaboun;
      case "city_rural_damascus_madaya":
        return tr.city_rural_damascus_madaya;
      case "city_rural_damascus_zabadani":
        return tr.city_rural_damascus_zabadani;
      case "city_rural_damascus_wafideen":
        return tr.city_rural_damascus_wafideen;
      case "city_rural_damascus_sayyida_zeinab":
        return tr.city_rural_damascus_sayyida_zeinab;
      case "city_rural_damascus_darayya":
        return tr.city_rural_damascus_darayya;
      case "city_rural_damascus_moadamiyeh":
        return tr.city_rural_damascus_moadamiyeh;
      case "city_rural_damascus_qatana":
        return tr.city_rural_damascus_qatana;
      case "city_rural_damascus_kiswah":
        return tr.city_rural_damascus_kiswah;
      case "city_rural_damascus_dmeir":
        return tr.city_rural_damascus_dmeir;
      case "city_rural_damascus_al_tall":
        return tr.city_rural_damascus_al_tall;
      case "city_rural_damascus_arbin":
        return tr.city_rural_damascus_arbin;
      case "city_rural_damascus_haran_al_awamid":
        return tr.city_rural_damascus_haran_al_awamid;
      case "city_rural_damascus_yabroud":
        return tr.city_rural_damascus_yabroud;
      case "city_rural_damascus_an_nabk":
        return tr.city_rural_damascus_an_nabk;
      case "city_rural_damascus_deir_atiyah":
        return tr.city_rural_damascus_deir_atiyah;
      case "city_rural_damascus_jayrud":
        return tr.city_rural_damascus_jayrud;
      case "city_rural_damascus_assal_al_ward":
        return tr.city_rural_damascus_assal_al_ward;

      // Aleppo
      case "city_aleppo_salah_al_din":
        return tr.city_aleppo_salah_al_din;
      case "city_aleppo_hanano":
        return tr.city_aleppo_hanano;
      case "city_aleppo_ashrafiyeh":
        return tr.city_aleppo_ashrafiyeh;
      case "city_aleppo_aziziyeh":
        return tr.city_aleppo_aziziyeh;
      case "city_aleppo_seif_al_dawla":
        return tr.city_aleppo_seif_al_dawla;
      case "city_aleppo_al_furqan":
        return tr.city_aleppo_al_furqan;
      case "city_aleppo_al_hamdaniya":
        return tr.city_aleppo_al_hamdaniya;
      case "city_aleppo_al_sukari":
        return tr.city_aleppo_al_sukari;
      case "city_aleppo_al_shaar":
        return tr.city_aleppo_al_shaar;
      case "city_aleppo_al_jamiliyeh":
        return tr.city_aleppo_al_jamiliyeh;
      case "city_aleppo_karm_al_jabal":
        return tr.city_aleppo_karm_al_jabal;
      case "city_aleppo_al_midan":
        return tr.city_aleppo_al_midan;
      case "city_aleppo_sheikh_maqsood":
        return tr.city_aleppo_sheikh_maqsood;
      case "city_aleppo_bustan_al_qasr":
        return tr.city_aleppo_bustan_al_qasr;
      case "city_aleppo_al_aziziyah":
        return tr.city_aleppo_al_aziziyah;
      case "city_aleppo_new_aleppo":
        return tr.city_aleppo_new_aleppo;
      case "city_aleppo_old_city":
        return tr.city_aleppo_old_city;
      case "city_aleppo_sheikh_najjar":
        return tr.city_aleppo_sheikh_najjar;
      case "city_aleppo_khan_al_asal":
        return tr.city_aleppo_khan_al_asal;
      case "city_aleppo_ramousah":
        return tr.city_aleppo_ramousah;
      case "city_aleppo_layramoun":
        return tr.city_aleppo_layramoun;
      case "city_aleppo_al_layramoun":
        return tr.city_aleppo_al_layramoun;
      case "city_aleppo_al_haydariyah":
        return tr.city_aleppo_al_haydariyah;

      // Homs
      case "city_homs_al_inshaat":
        return tr.city_homs_al_inshaat;
      case "city_homs_al_waer":
        return tr.city_homs_al_waer;
      case "city_homs_al_hamra":
        return tr.city_homs_al_hamra;
      case "city_homs_bab_tadmur":
        return tr.city_homs_bab_tadmur;
      case "city_homs_al_khaldiyeh":
        return tr.city_homs_al_khaldiyeh;
      case "city_homs_al_bayada":
        return tr.city_homs_al_bayada;
      case "city_homs_deir_ba_alba":
        return tr.city_homs_deir_ba_alba;
      case "city_homs_ghouta":
        return tr.city_homs_ghouta;
      case "city_homs_al_qusur":
        return tr.city_homs_al_qusur;
      case "city_homs_al_zahraa":
        return tr.city_homs_al_zahraa;
      case "city_homs_al_nuzha":
        return tr.city_homs_al_nuzha;
      case "city_homs_al_sabeel":
        return tr.city_homs_al_sabeel;
      case "city_homs_al_hamidiyah":
        return tr.city_homs_al_hamidiyah;
      case "city_homs_al_qarabis":
        return tr.city_homs_al_qarabis;
      case "city_homs_al_karama":
        return tr.city_homs_al_karama;
      case "city_homs_al_salam":
        return tr.city_homs_al_salam;
      case "city_homs_al_ghouta":
        return tr.city_homs_al_ghouta;
      case "city_homs_al_hosn":
        return tr.city_homs_al_hosn;
      case "city_homs_al_qaryatein":
        return tr.city_homs_al_qaryatein;
      case "city_homs_palmyra":
        return tr.city_homs_palmyra;

      // Hama
      case "city_hama_al_arbaeen":
        return tr.city_hama_al_arbaeen;
      case "city_hama_al_nasiriya":
        return tr.city_hama_al_nasiriya;
      case "city_hama_al_kareem":
        return tr.city_hama_al_kareem;
      case "city_hama_al_saboun":
        return tr.city_hama_al_saboun;
      case "city_hama_al_baath":
        return tr.city_hama_al_baath;
      case "city_hama_mhardeh":
        return tr.city_hama_mhardeh;
      case "city_hama_slimiyah":
        return tr.city_hama_slimiyah;
      case "city_hama_kafr_zita":
        return tr.city_hama_kafr_zita;
      case "city_hama_latamina":
        return tr.city_hama_latamina;
      case "city_hama_taybat_al_imam":
        return tr.city_hama_taybat_al_imam;
      case "city_hama_soran":
        return tr.city_hama_soran;
      case "city_hama_kafr_nabudah":
        return tr.city_hama_kafr_nabudah;
      case "city_hama_halfaya":
        return tr.city_hama_halfaya;
      case "city_hama_maharda":
        return tr.city_hama_maharda;
      case "city_hama_qamhana":
        return tr.city_hama_qamhana;
      case "city_hama_al_latamna":
        return tr.city_hama_al_latamna;
      case "city_hama_al_surmaniyah":
        return tr.city_hama_al_surmaniyah;
      case "city_hama_al_mazzeh_hama":
        return tr.city_hama_al_mazzeh_hama;
      case "city_hama_al_suqailabiya":
        return tr.city_hama_al_suqailabiya;
      case "city_hama_al_hamraa":
        return tr.city_hama_al_hamraa;

      // Latakia
      case "city_latakia_al_ramleh":
        return tr.city_latakia_al_ramleh;
      case "city_latakia_al_ziraa":
        return tr.city_latakia_al_ziraa;
      case "city_latakia_corniche":
        return tr.city_latakia_corniche;
      case "city_latakia_qastal_maaf":
        return tr.city_latakia_qastal_maaf;
      case "city_latakia_jableh":
        return tr.city_latakia_jableh;
      case "city_latakia_qardaha":
        return tr.city_latakia_qardaha;
      case "city_latakia_slunfeh":
        return tr.city_latakia_slunfeh;
      case "city_latakia_baniyas":
        return tr.city_latakia_baniyas;
      case "city_latakia_al_haffa":
        return tr.city_latakia_al_haffa;
      case "city_latakia_al_sheikh_daher":
        return tr.city_latakia_al_sheikh_daher;
      case "city_latakia_al_daatour":
        return tr.city_latakia_al_daatour;
      case "city_latakia_ras_al_basit":
        return tr.city_latakia_ras_al_basit;
      case "city_latakia_kessab":
        return tr.city_latakia_kessab;
      case "city_latakia_al_sanamayn":
        return tr.city_latakia_al_sanamayn;
      case "city_latakia_al_raml":
        return tr.city_latakia_al_raml;
      case "city_latakia_al_bayda":
        return tr.city_latakia_al_bayda;
      case "city_latakia_al_shamiya":
        return tr.city_latakia_al_shamiya;
      case "city_latakia_al_kabir":
        return tr.city_latakia_al_kabir;
      case "city_latakia_al_safa":
        return tr.city_latakia_al_safa;
      case "city_latakia_al_midan_latakia":
        return tr.city_latakia_al_midan_latakia;

      // Tartous
      case "city_tartous_tartous":
        return tr.city_tartous_tartous;
      case "city_tartous_al_sheikh_badr":
        return tr.city_tartous_al_sheikh_badr;
      case "city_tartous_baniyas":
        return tr.city_tartous_baniyas;
      case "city_tartous_corniche":
        return tr.city_tartous_corniche;
      case "city_tartous_dreikish":
        return tr.city_tartous_dreikish;
      case "city_tartous_rabea":
        return tr.city_tartous_rabea;
      case "city_tartous_mashta_al_hilou":
        return tr.city_tartous_mashta_al_hilou;
      case "city_tartous_bechmira":
        return tr.city_tartous_bechmira;
      case "city_tartous_al_hamidiyah":
        return tr.city_tartous_al_hamidiyah;
      case "city_tartous_al_dreikish":
        return tr.city_tartous_al_dreikish;
      case "city_tartous_al_kadmous":
        return tr.city_tartous_al_kadmous;
      case "city_tartous_al_safsafah":
        return tr.city_tartous_al_safsafah;
      case "city_tartous_al_sheikh_badr_center":
        return tr.city_tartous_al_sheikh_badr_center;
      case "city_tartous_al_tall":
        return tr.city_tartous_al_tall;
      case "city_tartous_al_kadmus":
        return tr.city_tartous_al_kadmus;
      case "city_tartous_al_rastan_tartous":
        return tr.city_tartous_al_rastan_tartous;
      case "city_tartous_al_sudan":
        return tr.city_tartous_al_sudan;
      case "city_tartous_al_sisiya":
        return tr.city_tartous_al_sisiya;
      case "city_tartous_al_bayada":
        return tr.city_tartous_al_bayada;
      case "city_tartous_al_hamra_tartous":
        return tr.city_tartous_al_hamra_tartous;

      // Idlib
      case "city_idlib_idlib":
        return tr.city_idlib_idlib;
      case "city_idlib_maarret_al_numan":
        return tr.city_idlib_maarret_al_numan;
      case "city_idlib_saraqib":
        return tr.city_idlib_saraqib;
      case "city_idlib_khan_sheikhoun":
        return tr.city_idlib_khan_sheikhoun;
      case "city_idlib_jisir_al_shughur":
        return tr.city_idlib_jisir_al_shughur;
      case "city_idlib_binnish":
        return tr.city_idlib_binnish;
      case "city_idlib_taftanaz":
        return tr.city_idlib_taftanaz;
      case "city_idlib_araq":
        return tr.city_idlib_araq;
      case "city_idlib_sarmin":
        return tr.city_idlib_sarmin;
      case "city_idlib_kafr_nabl":
        return tr.city_idlib_kafr_nabl;
      case "city_idlib_maaret_al_tamasrin":
        return tr.city_idlib_maaret_al_tamasrin;
      case "city_idlib_harem":
        return tr.city_idlib_harem;
      case "city_idlib_darkosh":
        return tr.city_idlib_darkosh;
      case "city_idlib_salqin":
        return tr.city_idlib_salqin;
      case "city_idlib_al_dana":
        return tr.city_idlib_al_dana;
      case "city_idlib_ram_hamdan":
        return tr.city_idlib_ram_hamdan;
      case "city_idlib_kafr_aya":
        return tr.city_idlib_kafr_aya;
      case "city_idlib_kafr_sajna":
        return tr.city_idlib_kafr_sajna;
      case "city_idlib_tal_karah":
        return tr.city_idlib_tal_karah;
      case "city_idlib_zardana":
        return tr.city_idlib_zardana;

      // Daraa
      case "city_daraa_daraa":
        return tr.city_daraa_daraa;
      case "city_daraa_busra_al_sham":
        return tr.city_daraa_busra_al_sham;
      case "city_daraa_nawa":
        return tr.city_daraa_nawa;
      case "city_daraa_jasem":
        return tr.city_daraa_jasem;
      case "city_daraa_tafss":
        return tr.city_daraa_tafss;
      case "city_daraa_mzeireb":
        return tr.city_daraa_mzeireb;
      case "city_daraa_sanamayn":
        return tr.city_daraa_sanamayn;
      case "city_daraa_inkhilal":
        return tr.city_daraa_inkhilal;
      case "city_daraa_hirak":
        return tr.city_daraa_hirak;
      case "city_daraa_dael":
        return tr.city_daraa_dael;
      case "city_daraa_al_sheikh_maskin":
        return tr.city_daraa_al_sheikh_maskin;
      case "city_daraa_namir":
        return tr.city_daraa_namir;
      case "city_daraa_ghabgab":
        return tr.city_daraa_ghabgab;
      case "city_daraa_al_yadouda":
        return tr.city_daraa_al_yadouda;
      case "city_daraa_al_tibneh":
        return tr.city_daraa_al_tibneh;
      case "city_daraa_tal_shihab":
        return tr.city_daraa_tal_shihab;
      case "city_daraa_khirbet_ghazaleh":
        return tr.city_daraa_khirbet_ghazaleh;
      case "city_daraa_al_harak":
        return tr.city_daraa_al_harak;
      case "city_daraa_al_jiza":
        return tr.city_daraa_al_jiza;
      case "city_daraa_al_manshiya":
        return tr.city_daraa_al_manshiya;

      // Deir Ezzor
      case "city_deir_ezzor_deir_ezzor":
        return tr.city_deir_ezzor_deir_ezzor;
      case "city_deir_ezzor_al_mayadeen":
        return tr.city_deir_ezzor_al_mayadeen;
      case "city_deir_ezzor_al_bukamal":
        return tr.city_deir_ezzor_al_bukamal;
      case "city_deir_ezzor_al_busayra":
        return tr.city_deir_ezzor_al_busayra;
      case "city_deir_ezzor_al_susah":
        return tr.city_deir_ezzor_al_susah;
      case "city_deir_ezzor_khasham":
        return tr.city_deir_ezzor_khasham;
      case "city_deir_ezzor_al_husseiniyah":
        return tr.city_deir_ezzor_al_husseiniyah;
      case "city_deir_ezzor_al_jura":
        return tr.city_deir_ezzor_al_jura;
      case "city_deir_ezzor_al_quriya":
        return tr.city_deir_ezzor_al_quriya;
      case "city_deir_ezzor_al_hawayej":
        return tr.city_deir_ezzor_al_hawayej;
      case "city_deir_ezzor_al_tayana":
        return tr.city_deir_ezzor_al_tayana;
      case "city_deir_ezzor_al_tabni":
        return tr.city_deir_ezzor_al_tabni;
      case "city_deir_ezzor_al_shuhail":
        return tr.city_deir_ezzor_al_shuhail;
      case "city_deir_ezzor_al_abu_kamal":
        return tr.city_deir_ezzor_al_abu_kamal;
      case "city_deir_ezzor_al_husainiya":
        return tr.city_deir_ezzor_al_husainiya;
      case "city_deir_ezzor_al_jezira":
        return tr.city_deir_ezzor_al_jezira;
      case "city_deir_ezzor_al_dhula":
        return tr.city_deir_ezzor_al_dhula;
      case "city_deir_ezzor_al_baghouz":
        return tr.city_deir_ezzor_al_baghouz;
      case "city_deir_ezzor_al_salihiyah":
        return tr.city_deir_ezzor_al_salihiyah;
      case "city_deir_ezzor_al_omar":
        return tr.city_deir_ezzor_al_omar;

      // Raqqa
      case "city_raqqa_raqqa":
        return tr.city_raqqa_raqqa;
      case "city_raqqa_tal_abyad":
        return tr.city_raqqa_tal_abyad;
      case "city_raqqa_al_tabqa":
        return tr.city_raqqa_al_tabqa;
      case "city_raqqa_al_mansoura":
        return tr.city_raqqa_al_mansoura;
      case "city_raqqa_al_karamah":
        return tr.city_raqqa_al_karamah;
      case "city_raqqa_al_karama":
        return tr.city_raqqa_al_karama;
      case "city_raqqa_al_hanida":
        return tr.city_raqqa_al_hanida;
      case "city_raqqa_al_kasrat":
        return tr.city_raqqa_al_kasrat;
      case "city_raqqa_al_resh":
        return tr.city_raqqa_al_resh;
      case "city_raqqa_al_hisba":
        return tr.city_raqqa_al_hisba;
      case "city_raqqa_al_rashid":
        return tr.city_raqqa_al_rashid;
      case "city_raqqa_al_jurneyyah":
        return tr.city_raqqa_al_jurneyyah;
      case "city_raqqa_al_sabkha":
        return tr.city_raqqa_al_sabkha;
      case "city_raqqa_al_hol":
        return tr.city_raqqa_al_hol;
      case "city_raqqa_al_rasafa":
        return tr.city_raqqa_al_rasafa;
      case "city_raqqa_al_sharakrak":
        return tr.city_raqqa_al_sharakrak;
      case "city_raqqa_al_khafsa":
        return tr.city_raqqa_al_khafsa;
      case "city_raqqa_al_masrab":
        return tr.city_raqqa_al_masrab;
      case "city_raqqa_al_tabaqa_dam":
        return tr.city_raqqa_al_tabaqa_dam;
      case "city_raqqa_al_qadisiya":
        return tr.city_raqqa_al_qadisiya;

      // Hasakah
      case "city_hasakah_qamishli":
        return tr.city_hasakah_qamishli;
      case "city_hasakah_hasakah":
        return tr.city_hasakah_hasakah;
      case "city_hasakah_malikiya":
        return tr.city_hasakah_malikiya;
      case "city_hasakah_ras_al_ayn":
        return tr.city_hasakah_ras_al_ayn;
      case "city_hasakah_al_shaddadi":
        return tr.city_hasakah_al_shaddadi;
      case "city_hasakah_amuda":
        return tr.city_hasakah_amuda;
      case "city_hasakah_derbasiya":
        return tr.city_hasakah_derbasiya;
      case "city_hasakah_tirbespi":
        return tr.city_hasakah_tirbespi;
      case "city_hasakah_al_mabrouka":
        return tr.city_hasakah_al_mabrouka;
      case "city_hasakah_al_yaarubiyah":
        return tr.city_hasakah_al_yaarubiyah;
      case "city_hasakah_al_hawl":
        return tr.city_hasakah_al_hawl;
      case "city_hasakah_al_himma":
        return tr.city_hasakah_al_himma;
      case "city_hasakah_al_ghazl":
        return tr.city_hasakah_al_ghazl;
      case "city_hasakah_al_kasra":
        return tr.city_hasakah_al_kasra;
      case "city_hasakah_al_markada":
        return tr.city_hasakah_al_markada;
      case "city_hasakah_al_tayyana":
        return tr.city_hasakah_al_tayyana;
      case "city_hasakah_al_sweidiya":
        return tr.city_hasakah_al_sweidiya;
      case "city_hasakah_al_khaldiya":
        return tr.city_hasakah_al_khaldiya;
      case "city_hasakah_al_jawadiyah":
        return tr.city_hasakah_al_jawadiyah;
      case "city_hasakah_al_talaq":
        return tr.city_hasakah_al_talaq;

      // Quneitra
      case "city_quneitra_quneitra":
        return tr.city_quneitra_quneitra;
      case "city_quneitra_khan_arnabah":
        return tr.city_quneitra_khan_arnabah;
      case "city_quneitra_baath_city":
        return tr.city_quneitra_baath_city;
      case "city_quneitra_al_rafid":
        return tr.city_quneitra_al_rafid;
      case "city_quneitra_jubata_al_khashab":
        return tr.city_quneitra_jubata_al_khashab;
      case "city_quneitra_hadar":
        return tr.city_quneitra_hadar;
      case "city_quneitra_al_qahtaniyah":
        return tr.city_quneitra_al_qahtaniyah;
      case "city_quneitra_bir_ajam":
        return tr.city_quneitra_bir_ajam;
      case "city_quneitra_masharah":
        return tr.city_quneitra_masharah;

      // As-Suwayda
      case "city_as_suwayda_as_suwayda":
        return tr.city_as_suwayda_as_suwayda;
      case "city_as_suwayda_salkhad":
        return tr.city_as_suwayda_salkhad;
      case "city_as_suwayda_shahba":
        return tr.city_as_suwayda_shahba;
      case "city_as_suwayda_qanawat":
        return tr.city_as_suwayda_qanawat;
      case "city_as_suwayda_al_qurayya":
        return tr.city_as_suwayda_al_qurayya;
      case "city_as_suwayda_ariqah":
        return tr.city_as_suwayda_ariqah;
      case "city_as_suwayda_al_mazraa":
        return tr.city_as_suwayda_al_mazraa;
      case "city_as_suwayda_thaala":
        return tr.city_as_suwayda_thaala;
      case "city_as_suwayda_shaqqa":
        return tr.city_as_suwayda_shaqqa;
      case "city_as_suwayda_al_ruha":
        return tr.city_as_suwayda_al_ruha;

      default:
        return resolvedKey;
    }
  }
}

String _resolveCityKey(String key, String? governorateKey) {
  if (key.startsWith("city_")) {
    return key;
  }
  if (governorateKey == null || governorateKey.isEmpty) {
    return key;
  }
  return "city_${governorateKey}_$key";
}
