class LocationData {
  static const String damascus = "damascus";
  static const String ruralDamascus = "rural_damascus";
  static const String aleppo = "aleppo";
  static const String homs = "homs";
  static const String hama = "hama";
  static const String latakia = "latakia";
  static const String tartous = "tartous";
  static const String idlib = "idlib";
  static const String daraa = "daraa";
  static const String deirEzzor = "deir_ezzor";
  static const String raqqa = "raqqa";
  static const String hasakah = "hasakah";

  static const List<String> governorates = [
    damascus,
    ruralDamascus,
    aleppo,
    homs,
    hama,
    latakia,
    tartous,
    idlib,
    daraa,
    deirEzzor,
    raqqa,
    hasakah,
  ];

  static const Map<String, List<String>> cities = {
    /// ---------------- DAMASCUS ----------------
    damascus: [
      "mazzeh",
      "kafrsouseh",
      "barzeh",
      "meidan",
      "ruken_al_din",
      "bab_touma",
      "bab_sharqi",
      "tishreen",
      "al_qanawat",
      "abu_rummaneh",
      "shaalan",
      "dummar",
      "al_midan",
      "kassaa",
      "old_damascus",
      "qasioun",
      "adawi",
      "al_amara",
      "abu_jamal",
      "harika",
    ],

    /// ---------------- RURAL DAMASCUS ----------------
    ruralDamascus: [
      "douma",
      "harasta",
      "zamalka",
      "jobar",
      "qaboun",
      "madaya",
      "zabadani",
      "wafideen",
      "sayyida_zeinab",
      "darayya",
      "moadamiyeh",
      "qatana",
      "kiswah",
      "dmeir",
      "al_tall",
      "arbin",
      "haran_al_awamid",
      "yabroud",
      "an_nabk",
      "deir_atiyah",
      "jayrud",
      "assal_al_ward",
    ],

    /// ---------------- ALEPPO ----------------
    aleppo: [
      "salah_al_din",
      "hanano",
      "ashrafiyeh",
      "aziziyeh",
      "seif_al_dawla",
      "al_furqan",
      "al_hamdaniya",
      "al_sukari",
      "al_shaar",
      "al_jamiliyeh",
      "karm_al_jabal",
      "al_midan",
      "sheikh_maqsood",
      "bustan_al_qasr",
      "al_aziziyah",
      "new_aleppo",
      "old_city",
      "sheikh_najjar",
      "khan_al_asal",
      "ramousah",
      "layramoun",
      "al_layramoun",
      "al_haydariyah",
    ],

    /// ---------------- HOMs ----------------
    homs: [
      "al_inshaat",
      "al_waer",
      "al_hamra",
      "bab_tadmur",
      "al_khaldiyeh",
      "al_bayada",
      "deir_ba_alba",
      "ghouta",
      "al_qusur",
      "al_zahraa",
      "al_nuzha",
      "al_sabeel",
      "al_hamidiyah",
      "al_qarabis",
      "al_karama",
      "al_salam",
      "al_ghouta",
      "al_hosn",
      "al_qaryatein",
      "palmyra",
    ],

    /// ---------------- HAMA ----------------
    hama: [
      "al_arbaeen",
      "al_nasiriya",
      "al_kareem",
      "al_saboun",
      "al_baath",
      "mhardeh",
      "slimiyah",
      "kafr_zita",
      "latamina",
      "taybat_al_imam",
      "soran",
      "kafr_nabudah",
      "halfaya",
      "maharda",
      "qamhana",
      "al_latamna",
      "al_surmaniyah",
      "al_mazzeh_hama",
      "al_suqailabiya",
      "al_hamraa",
    ],

    /// ---------------- LATTAKIA ----------------
    latakia: [
      "al_ramleh",
      "al_ziraa",
      "corniche",
      "qastal_maaf",
      "jableh",
      "qardaha",
      "slunfeh",
      "baniyas",
      "al_haffa",
      "al_sheikh_daher",
      "al_daatour",
      "ras_al_basit",
      "kessab",
      "al_sanamayn",
      "al_raml",
      "al_bayda",
      "al_shamiya",
      "al_kabir",
      "al_safa",
      "al_midan_latakia",
    ],

    /// ---------------- TARTOUS ----------------
    tartous: [
      "tartous",
      "al_sheikh_badr",
      "baniyas",
      "corniche",
      "dreikish",
      "rabea",
      "mashta_al_hilou",
      "bechmira",
      "al_hamidiyah",
      "al_dreikish",
      "al_kadmous",
      "al_safsafah",
      "al_sheikh_badr_center",
      "al_tall",
      "al_kadmus",
      "al_rastan_tartous",
      "al_sudan",
      "al_sisiya",
      "al_bayada",
      "al_hamra_tartous",
    ],

    /// ---------------- IDLIB ----------------
    idlib: [
      "idlib",
      "maarret_al_numan",
      "saraqib",
      "khan_sheikhoun",
      "jisir_al_shughur",
      "binnish",
      "taftanaz",
      "araq",
      "sarmin",
      "kafr_nabl",
      "maaret_al_tamasrin",
      "harem",
      "darkosh",
      "salqin",
      "al_dana",
      "ram_hamdan",
      "kafr_aya",
      "kafr_sajna",
      "tal_karah",
      "zardana",
    ],

    /// ---------------- DARAA ----------------
    daraa: [
      "daraa",
      "busra_al_sham",
      "nawa",
      "jasem",
      "tafss",
      "mzeireb",
      "sanamayn",
      "inkhilal",
      "hirak",
      "dael",
      "al_sheikh_maskin",
      "namir",
      "ghabgab",
      "al_yadouda",
      "al_tibneh",
      "tal_shihab",
      "khirbet_ghazaleh",
      "al_harak",
      "al_jiza",
      "al_manshiya",
    ],

    /// ---------------- DEIR EZZOR ----------------
    deirEzzor: [
      "deir_ezzor",
      "al_mayadeen",
      "al_bukamal",
      "al_busayra",
      "al_susah",
      "khasham",
      "al_husseiniyah",
      "al_jura",
      "al_quriya",
      "al_hawayej",
      "al_tayana",
      "al_tabni",
      "al_shuhail",
      "al_abu_kamal",
      "al_husainiya",
      "al_jezira",
      "al_dhula",
      "al_baghouz",
      "al_salihiyah",
      "al_omar",
    ],

    /// ---------------- RAQQA ----------------
    raqqa: [
      "raqqa",
      "tal_abyad",
      "al_tabqa",
      "al_mansoura",
      "al_karamah",
      "al_karama",
      "al_hanida",
      "al_kasrat",
      "al_resh",
      "al_hisba",
      "al_rashid",
      "al_jurneyyah",
      "al_sabkha",
      "al_hol",
      "al_rasafa",
      "al_sharakrak",
      "al_khafsa",
      "al_masrab",
      "al_tabaqa_dam",
      "al_qadisiya",
    ],

    /// ---------------- HASAKAH ----------------
    hasakah: [
      "qamishli",
      "hasakah",
      "malikiya",
      "ras_al_ayn",
      "al_shaddadi",
      "amuda",
      "derbasiya",
      "tirbespi",
      "al_mabrouka",
      "al_yaarubiyah",
      "al_hawl",
      "al_himma",
      "al_ghazl",
      "al_kasra",
      "al_markada",
      "al_tayyana",
      "al_sweidiya",
      "al_khaldiya",
      "al_jawadiyah",
      "al_talaq",
    ],
  };

  static List<String> getCities(String governorate) {
    return cities[governorate] ?? [];
  }
}
